---
version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testtest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  # backend:
  #   build: ./rails-app
  #   command: bash -c "bundle && bundle exec rails s -p 3000 -b '0.0.0.0'"

  #   volumes:
  #     - ./rails-app:/srv/rails-app
  #     - bundler_cache_rails:/usr/local/bundle
  #   ports:
  #     - '3000:3000'
  #   working_dir: /srv/rails-app
  #   depends_on:
  #     - "db"
  backend:
    build: ./hanami
    command: bash -c "cd /srv/app && bundle && bundle exec hanami server --port=3000 --host=0.0.0.0"
    volumes:
      - ./hanami:/srv/app
      - bundler_cache_hanami:/usr/local/bundle
    ports:
      - '3000:3000'
    working_dir: /srv/hanami
    depends_on:
      - "db"
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/srv/frontend
    ports:
      - '3001:3001'
    depends_on:
      - "backend"
volumes:
  bundler_cache_rails:
  bundler_cache_hanami:
